Default localidentifier
browserstack/nightwatch-browserstack pull request #55
Opened 2022-11-08 05:06 UTC by 07souravkunda

2022-11-09 06:20 UTC, kamal-kaur04 requested changes

2022-11-09 06:20 UTC, kamal-kaur04 commented on tests/local/local_test.js
> +        this.assert.ok(title.toLowerCase().includes('browserstack'));
I think we can check for exact title

2022-11-11 11:10 UTC, kamal-kaur04 approved these changes

2022-11-11 12:23 UTC, francisf approved these changes

2022-11-11 12:23 UTC, merged